name: backend-ci
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
env:
  # Set Python Version
  PYTHON_VERSION: '3.10'

jobs:
  backend-lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python '3.10' from env
    uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Dependency
      working-directory: starter/backend
      run: pipenv install

    - name: Lint
      working-directory: starter/backend
      run: pipenv run lint

    - name: Test
      working-directory: starter/backend
      run: pipenv run test


  backend-build:
      runs-on: ubuntu-latest
      needs: [backend-lint-test]

      steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Python '3.10' from env
      uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Build
        working-directory: starter/backend
        run: |
          pipenv run serve
          echo "run success"
    