name: backend-ci
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  
env:
  # Set Python Version
  PYTHON_VERSION: '3.10'

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python '3.10' from env
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Dependency
      working-directory: starter/backend
      run: |
        pip install pipenv
        pip install flake8
        pipenv install

    - name: Lint
      working-directory: starter/backend
      run: pipenv run lint

  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python '3.10' from env
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Dependency
      working-directory: starter/backend
      run: |
        pip install pipenv
        pip install flake8
        pipenv install

    - name: Test
      working-directory: starter/backend
      run: pipenv run test


  backend-build:
      runs-on: ubuntu-latest
      needs: [backend-lint, backend-test]

      steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build
        working-directory: starter/backend
        run: |
          docker build --tag backend-service:latest .
          echo "run success"
    