name: frontend-ci
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  
env:
  # Set Node.js Version
  NODE_VERSION: '18.x'

jobs:
  frontend-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js '18.x' from env
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Install Dependency
      working-directory: starter/frontend
      run: npm ci

    - name: Lint
      working-directory: starter/frontend
      run: npm run lint -- --fix

  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js '18.x' from env
      uses: actions/setup-node@v3
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Install Dependency
      working-directory: starter/frontend
      run: npm ci

    - name: Test
      working-directory: starter/frontend
      run: npm run test --passWithNoTests


  frontend-build:
      runs-on: ubuntu-latest
      needs: [frontend-lint, frontend-test]

      steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js '18.x' from env
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install Dependency
        working-directory: starter/frontend
        run: npm ci
        
      - name: Build
        working-directory: starter/frontend
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=frontend-service:latest .
          echo "build success"
          docker run --name frontend-service -p 3000:3000 -d frontend-service
          echo "run success"
    